# Generated by Django 2.0.5 on 2018-12-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='https://i.ibb.co/1fw5QMB/default-image.jpg', max_length=510, null=True),
        ),
    ]
